Pull request #116: [READY] laas-hosts inventory sync implementation
Merge in OST/laas-reflab from import-rework to iol-dev

Squashed commit of the following:

commit 9de6182c4c4ae4fc8ea407736d8f25e57fa283be
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Thu May 29 13:39:30 2025 -0400

    feat: added arch field in hostblob back

commit f6fd0ab226dfd6d45b070d2aa13227b5f3b524b2
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Thu May 29 10:42:42 2025 -0400

    fixed dockerfile

commit ed07b4bf6ba3691126b5f7ff9f649bf716851871
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Thu May 29 10:19:20 2025 -0400

    feast: fixed clippy warnings, dependencies and wrote Dockerfile

commit 3b5084a7371e7ff034e3bda1d7739d1a81d8cd27
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Fri May 23 15:56:59 2025 -0400

    feat: import code MVP

commit aafd2a290176ae7a742ed7bf073e5742bd2723ef
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Thu May 22 15:57:31 2025 -0400

    checkpoint: initial import implementation (broken)

commit e882b6cabaa5a382fcb50686b789eb9c15dc9782
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Wed May 21 15:38:53 2025 -0400

    feat: color correction

commit f76e16cbf72c42de8c9b3eab9befef8bc19e6a2b
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Wed May 21 15:35:54 2025 -0400

    feat: working host validation

commit c6f4fe66b2794d141473ac03557c908b3679029c
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Tue May 20 16:24:45 2025 -0400

    checkpoint: work 5-20-25, (broken)

commit 2039ae12e5a63d243f83bb144128b69f6085d3a2
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Mon May 19 16:03:36 2025 -0400

    feat: reorg, better error handling, fetch module

commit 11e53a917579695f5d83d66e73d0a5f529e30057
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Fri May 16 15:48:00 2025 -0400

    broken: additional verification logic, better error handling

commit ac1edd5b75191c163b73b7a58eaca1a2e80ffac2
Author: Kidan Nelson <knelson@iol.unh.edu>
Date:   Thu May 15 16:52:54 2025 -0400

    feat: initial commit (broken)

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -61,6 +61,28 @@ command = "cargo"
 args = ["sqlx", "migrate", "run"]
 dependencies = ["setup-db", "wait-db"]
 
+# Load a new database from a SQL dump file
+# Usage: cargo make restore-db --env SQL_DUMP=path/to/dump.sql
+[tasks.restore-db]
+workspace = false
+condition = { profiles = ["development"] }
+dependencies = ["setup-db", "wait-db"]
+script = [
+  '''
+  if [ -z "${SQL_DUMP}" ]; then
+    echo "Error: SQL_DUMP environment variable not set."
+    exit 1
+  fi
+
+  echo "Restoring database from ${SQL_DUMP}..."
+
+  docker cp ${SQL_DUMP} ${CONTAINER_NAME}:/tmp/dump.sql
+  docker exec -u postgres ${CONTAINER_NAME} sh -c "psql -d ${DATABASE_NAME} -f /tmp/dump.sql"
+
+  echo "Database restore completed."
+  ''',
+]
+
 # Prepares SQLx offline queries (required before building)
 # Depends on: migrate
 [tasks.prepare]
